name: Ftrack Event Manager
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Install and Build
      run: |
          npm install
          npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
